-- Salespersons Table
CREATE TABLE SALESPERSONS (
	SALES_PERSON_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100)
);

-- Cars Table
CREATE TABLE CARS (
	CAR_ID SERIAL PRIMARY KEY,
	CAR_MAKE VARCHAR(100),
	CAR_MODEL VARCHAR(100)
);

-- Customer Table
CREATE TABLE CUSTOMER (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100)
);

-- Invoice Table
CREATE TABLE INVOICE (
	INVOICE_ID SERIAL PRIMARY KEY,
	CAR_ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- Mechanic Table
CREATE TABLE MECHANIC (
	MECHANIC_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100)
);

-- Service Table
CREATE TABLE SERVICE (
	TICKET_ID SERIAL PRIMARY KEY,
	SERVICE_NAME VARCHAR(150),
	CUSTOMER_ID INTEGER NOT NULL,
	CAR_ID INTEGER NOT NULL,
	MECHANIC_ID INTEGER NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
	FOREIGN KEY (MECHANIC_ID) REFERENCES MECHANIC(MECHANIC_ID)
);

-- Parts Table
CREATE TABLE PARTS (
	PARTS_ID SERIAL PRIMARY KEY,
	PART_NAME VARCHAR(150),
	TICKET_ID INTEGER NOT NULL,
	FOREIGN KEY (TICKET_ID) REFERENCES SERVICE(TICKET_ID)
);








