CREATE OR REPLACE FUNCTION ADD_SALESPERSON(_SALES_PERSON_ID INTEGER, _FIRST_NAME VARCHAR, _LAST_NAME VARCHAR)
RETURNS VOID
AS $MAIN$
BEGIN 
	INSERT INTO SALESPERSONS(SALES_PERSON_ID, FIRST_NAME, LAST_NAME)
	VALUES(_SALES_PERSON_ID, _FIRST_NAME, _LAST_NAME);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_SALESPERSON(001, 'Carlos', 'Santiago');
SELECT ADD_SALESPERSON(002, 'Kevin', 'James');
SELECT ADD_SALESPERSON(003, 'Caden', 'Michael');
SELECT ADD_SALESPERSON(004, 'Kayla', 'Morgan');

CREATE OR REPLACE FUNCTION ADD_CAR(_CAR_ID INTEGER, _CAR_MAKE VARCHAR, _CAR_MODEL VARCHAR)
RETURNS VOID
AS $MAIN$
BEGIN 
	INSERT INTO CARS(CAR_ID, CAR_MAKE, CAR_MODEL) 
	VALUES(_CAR_ID, _CAR_MAKE, _CAR_MODEL);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_CAR(001, 'Mazda', 'Mazda3');
SELECT ADD_CAR(002, 'Mazda', 'CX-30');
SELECT ADD_CAR(003, 'Ford', 'Mustang');
SELECT ADD_CAR(004, 'Chevrolet', 'Camaro');

CREATE OR REPLACE FUNCTION ADD_CUSTOMER(_CUSTOMER_ID INTEGER, _FIRST_NAME VARCHAR, _LAST_NAME VARCHAR)
RETURNS VOID 
AS $MAIN$
BEGIN 
	INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME)
	VALUES(_CUSTOMER_ID, _FIRST_NAME, _LAST_NAME);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_CUSTOMER(001, 'Michael', 'Jackson');
SELECT ADD_CUSTOMER(002, 'Lebron', 'James');
SELECT ADD_CUSTOMER(003, 'Stephen', 'Curry');
SELECT ADD_CUSTOMER(004, 'Janette', 'Jackson');

CREATE OR REPLACE FUNCTION ADD_INVOICE(_INVOICE_ID INTEGER, _CAR_ID INTEGER, _CUSTOMER_ID INTEGER)
RETURNS VOID 
AS $MAIN$
BEGIN 
	INSERT INTO INVOICE(INVOICE_ID, CAR_ID, CUSTOMER_ID)
	VALUES(_INVOICE_ID, _CAR_ID, _CUSTOMER_ID);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_INVOICE(001, 001, 001);
SELECT ADD_INVOICE(002, 002, 002);
SELECT ADD_INVOICE(003, 003, 003);
SELECT ADD_INVOICE(004, 004, 004);

CREATE OR REPLACE FUNCTION ADD_MECHANIC(_MECHANIC_ID INTEGER, _FIRST_NAME VARCHAR, _LAST_NAME VARCHAR)
RETURNS VOID
AS $MAIN$
BEGIN 
	INSERT INTO MECHANIC(MECHANIC_ID, FIRST_NAME, LAST_NAME)
	VALUES(_MECHANIC_ID, _FIRST_NAME, _LAST_NAME);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_MECHANIC(001, 'Michael', 'Townsend');
SELECT ADD_MECHANIC(002, 'Trevor', 'Philips');
SELECT ADD_MECHANIC(003, 'Franklin', 'Clinton');
SELECT ADD_MECHANIC(004, 'Lester', 'Crest');

CREATE OR REPLACE FUNCTION ADD_SERVICE(_TICKET_ID INTEGER, _SERVICE_NAME VARCHAR, _CUSTOMER_ID INTEGER, _CAR_ID INTEGER, _MECHANIC_ID INTEGER)
RETURNS VOID
AS $MAIN$
BEGIN 
	INSERT INTO SERVICE(TICKET_ID, SERVICE_NAME, CUSTOMER_ID, CAR_ID, MECHANIC_ID)
	VALUES(_TICKET_ID, _SERVICE_NAME, _CUSTOMER_ID, _CAR_ID, _MECHANIC_ID);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_SERVICE(001, 'Oil Change', 001, 001, 001);
SELECT ADD_SERVICE(002, 'Tire Rotation', 002, 002, 002);
SELECT ADD_SERVICE(003, 'Replace Starter', 003, 003, 003);
SELECT ADD_SERVICE(004, 'Replace Head Gasket', 004, 004, 004);

CREATE OR REPLACE FUNCTION ADD_PART(_PARTS_ID INTEGER, _PART_NAME VARCHAR, _TICKET_ID INTEGER)
RETURNS VOID 
AS $MAIN$
BEGIN 
	INSERT INTO PARTS(PARTS_ID, PART_NAME, TICKET_ID)
	VALUES(_PARTS_ID, _PART_NAME, _TICKET_ID);
END;
$MAIN$
LANGUAGE PLPGSQL

SELECT ADD_PART(001, 'Starter', 003);
SELECT ADD_PART(002, 'Head Gasket', 004);























